### ISSUE TITLE
Method: getTranslations does not exist

### ISSUE THREAD

**Issue by StanBarrows** [mrmonat/nova-translatable#1]
Hey first of all, a nice idea to implement this.

Unfortunately when I follow your installation guide, I'receive this error.

![install](https://user-images.githubusercontent.com/10268813/44589058-cb82c980-a7b7-11e8-84d8-28ff62898af0.png)

Any suggestions?

**Comment by mrmonat** [comment]
are you using https://github.com/spatie/spatie-translatable in your project and the ```HasTranslations``` Trait on your Model?

**Comment by StanBarrows** [comment]
No, of course not.. Hello weekend

Thanks for the quick advise! 

Have a nice weekend!
