### ISSUE TITLE
Global search not working with translatable package

### ISSUE THREAD

**Issue by devmsh** [mrmonat/nova-translatable#10]
Global search and resource search are powerful tools in Nova, but sadly they did not work with translatable package if the title or name field is translatable.

I think this is a killer issue that need to be addressed. It may be out of scope of this package itself, but how can we address this issue?

**Comment by mrmonat** [comment]
For me its working when using mysql... Just add ```'title'``` or ```'name'``` to 

```
/**
  * The columns that should be searched.
  *
  * @var array
  */
  public static $search = [
      'id', 'name',
  ];
```

The resulting "search query" is:
```select * from `product_families ` where (`product_families `.`name` like '%test%') order by `product_families `.`id` desc limit 26 offset 0```
