### ISSUE TITLE
Does not work with the new "withFiles()" method

### ISSUE THREAD

**Issue by francoislevesque** [mrmonat/nova-translatable#14]
The Field does not work with the new "withFiles()" method when using Trix:

```
Translatable::make('Content')->trix()
                ->withFiles('public')
                ->hideFromIndex()
                ->sortable()
                ->rules('required'),
```

It throws `Call to undefined method MrMonat\\Translatable\\Translatable::withFiles()`

**Comment by mrmonat** [comment]
At the moment adding support for file uploads would mean to copy the entire logic from the original Nova Trix Field Vue Component to the Translatable Vue Component, which seems not right.
I'm currently working on v2 of this package, and will try to implement this in version 2.0

**Comment by n0n0n0n0** [comment]
any updates?
