### ISSUE TITLE
Support for withFiles when using Trix

### ISSUE THREAD

**Issue by v1nk0** [mrmonat/nova-translatable#19]
I'm using nova-translatable for a Trix field. This works well because of the Trix support that this package has. With Nova, the Trix field has a "withFiles" method which makes it possible to upload files into the editor, see: https://nova.laravel.com/docs/1.0/resources/fields.html#field-types

Is it possible to add this possibility -> being able to activate the file-upload ability of the Trix editor.

**Comment by m-kas** [comment]
👍 I would much appreciate such feature as well.

**Comment by darki73** [comment]
Yep, this would be amazing. The only thing i am missing right now in this package.

Keep it up, really amazing work!

**Comment by mrmonat** [comment]
Hi,
I can understand that it would be nice to have that functionality, but it isn't as easy to implement as the other "basic" field types. It is a similar problem like described in #4. 

If you need this functionality i would suggest to use https://github.com/spatie/nova-translatable.

**Comment by vguerrerobosch** [comment]
Hi,

Currently spatie/nova-translatable does not support withFiles method. See issue [#18](https://github.com/spatie/nova-translatable/issues/18).
