### ISSUE TITLE
Please update to require spatie/laravel-translatable": "3.*"

### ISSUE THREAD

**Issue by tanthammar** [mrmonat/nova-translatable#22]
Current version requires"spatie/laravel-translatable": "^2.2"
Please update to "spatie/laravel-translatable": "3.*"
Unable to install.

**Comment by jimmitjoo** [comment]
Submitted a pull request for this: https://github.com/mrmonat/nova-translatable/pull/25

**Comment by mrmonat** [comment]
Fixed in 1.2.0.
