### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by jarda256sparktech** [mrmonat/nova-translatable#23]
Hi, I have a problem with creating translatable field. I have spatie/laravel-translatable so my model looks like this however i am not able to show any of these fields as translatable...what can be wrong
`use Spatie\Translatable\HasTranslations;

class Manufacturer extends Model
{
	use HasTranslations;

	protected $translatable = ['name','description','description_short','meta_title','meta_keywords','meta_description'];
`

**Comment by mrmonat** [comment]
Could you please provide more information? What exactly doesn't work? Could you share your Nova Resource for the `Manufacturer` model?
