### ISSUE TITLE
Allow to create "translatable" images

### ISSUE THREAD

**Issue by darki73** [mrmonat/nova-translatable#24]
Hey, really amazing project.

I have a request though, it would be nice to provide ability to create translatable images.

Lets say we have an image field in the database with the json column type.
If we are creating a blog post with multiple locales, we also need to have an ability to attach image for those locales. This is quite useful if main post image contains text in different locales.

**Comment by mrmonat** [comment]
Hi,
please look at explanation in #4 and #19, it is too much code that would be duplicated from native nova fields to support this field type right now. If you need this functionality i would suggest using this package: https://github.com/spatie/nova-translatable
