### ISSUE TITLE
show the translated attribute in current app locale

### ISSUE THREAD

**Issue by oxygencms** [mrmonat/nova-translatable#27]
Is it possible to have the current app locale dictate which translation tab is selected by default when the edit/show page is loaded? I mean when I have my app locale set to say 'bg' I want to see the Bulgarian translation of the field selected by default then click to check out the rest of the translations. Can you help with this? Thanks. Cheers!

**Comment by milewski** [comment]
It should be pretty simple to fix this issue, I just tried fixing this locally but i cant get the dependencies of this package to work... it might be outdated

@mrmonat can you push a working packages-lock.json to this repo? so i can get this working locally i then can send a pull request fixing this issue, thanks. or perhaps you dont want to maintain this repo anymore you can transfer it to me thanks

**Comment by reppair** [comment]
@mrmonat Nice any update on this one?

**Comment by maherelgamil** [comment]
@mrmonat any updates here ?

**Comment by mrmonat** [comment]
Implemented in #43
