### ISSUE TITLE
Translation Indicator

### ISSUE THREAD

**Issue by StanBarrows** [mrmonat/nova-translatable#3]
I've build the same component for one of my projects. The only difference, I used an indicator to show if the translation was already filled out.

![component](https://user-images.githubusercontent.com/10268813/44590404-5ca76f80-a7bb-11e8-9a32-a90e1ceed89b.png)

Do you have any plans to implement this functionality? Or would you accept a Pull-Request for this? 

Cheers,
Stan

**Comment by mrmonat** [comment]
I like the idea to show something like this, but I just tried a little bit and I came to the result that I like the simple and minimal style of the "locale buttons" and that putting an icon next to them doesn't look quite right for me.

Maybe I would accept a PR in the future when this package grows on features, but right now I wouldn't like to add it.

But maybe you could create your own package and release it, feel free to use any of my code :)
