### ISSUE TITLE
A "required" field doesn't have a red asterisk

### ISSUE THREAD

**Issue by andypa** [mrmonat/nova-translatable#37]
Hi

The default field in nova has an asterisk if it is required but unfortunately, this field doesn't have that. I would create a pull request in the next couple of hours, would you consider merging it?

Best regards,
Andy

PS: Here's the [PR](https://github.com/mrmonat/nova-translatable/pull/38)

**Comment by mrmonat** [comment]
Thank you, merged your PR.
