### ISSUE TITLE
Support Laravel-translatable 5.*

### ISSUE THREAD

**Issue by mattstauffer** [mrmonat/nova-translatable#47]
Laravel-translatable has moved to a 5.* series, but this package locks 4.*.

Could you please tag a release that supports 5.*? Thanks!

**Comment by mrmonat** [comment]
I just tagged a new release (2.2.0) with support for both PHP 8 and spatie/laravel-translatable >= 5.0

**Comment by mattstauffer** [comment]
Thanks @mrmonat!
