### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by freekmurze** [mrmonat/nova-translatable#7]
Hi,

thanks for creating this package and using ours as an underlying dependency.

The current name of your package could make people think that we created it. Could you rename it so it doesn't have `spatie` in it anymore? 

I'd also accept a PR to `spatie/laravel-translatable` that adds a link in the readme to your nova package.

Thanks!

**Comment by mrmonat** [comment]
Yes of course, thank you for awesome packages :)
