### ISSUE TITLE
Could not find a matching version

### ISSUE THREAD

**Issue by devmsh** [mrmonat/nova-translatable#8]
```
Could not find a matching version of package mrmonat/nova-translatable. Check the package spelling, your version constraint and that the package is available in a   
  stability which matches your minimum-stability (stable).  
```

it seems the error related to the repo name change?

**Comment by mrmonat** [comment]
Yes I think so too, I get the same error at the moment... Seems like composer is not yet finding the new package... It's definitely uploaded (see https://packagist.org/packages/mrmonat/nova-translatable) so I hope the error will be gone soon...

**Comment by mrmonat** [comment]
Working now with v1.1.1
